<a href="https://colab.research.google.com/github/Jestika-safitri/jestika/blob/main/labeling_data_lexicond.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download("vader_lexicon")
import pandas as pd
data = pd.read_csv("databersihfinaljestika.csv")
data = data.dropna()
print(data.head())

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

                                               posts
0  kerap termarjinalisasi perempuan perempuan pen...
1  tindakan semacam ini dapat dilaporkan kepada p...
2         inilah contoh kekerasan dalam rumah tangga
3  sertu iswanto babinsa kalurahan srihatjo bersa...
4  kerap termarjinalisasi perempuan perempuan pen...

In [ ]:
sentiments = SentimentIntensityAnalyzer()
data["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in data["posts"]]
data["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in data["posts"]]
data["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in data["posts"]]
data['Compound'] = [sentiments.polarity_scores(i)["compound"] for i in data["posts"]]
data.head()

,posts,Positive,Negative,Neutral,Compound
0,kerap termarjinalisasi perempuan perempuan pen...,0.0,0.0,1.0,0.0
1,tindakan semacam ini dapat dilaporkan kepada p...,0.0,0.0,1.0,0.0
2,inilah contoh kekerasan dalam rumah tangga,0.0,0.0,1.0,0.0
3,sertu iswanto babinsa kalurahan srihatjo bersa...,0.0,0.0,1.0,0.0
4,kerap termarjinalisasi perempuan perempuan pen...,0.0,0.0,1.0,0.0

In [ ]:
score = data["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
data["Sentiment"] = sentiment
data.head()

,posts,Positive,Negative,Neutral,Compound,Sentiment
0,kerap termarjinalisasi perempuan perempuan pen...,0.0,0.0,1.0,0.0,Neutral
1,tindakan semacam ini dapat dilaporkan kepada p...,0.0,0.0,1.0,0.0,Neutral
2,inilah contoh kekerasan dalam rumah tangga,0.0,0.0,1.0,0.0,Neutral
3,sertu iswanto babinsa kalurahan srihatjo bersa...,0.0,0.0,1.0,0.0,Neutral
4,kerap termarjinalisasi perempuan perempuan pen...,0.0,0.0,1.0,0.0,Neutral

In [ ]:
data.head(1000)

,posts,Positive,Negative,Neutral,Compound,Sentiment
0,kerap termarjinalisasi perempuan perempuan pen...,0.000,0.0,1.000,0.0000,Neutral
1,tindakan semacam ini dapat dilaporkan kepada p...,0.000,0.0,1.000,0.0000,Neutral
2,inilah contoh kekerasan dalam rumah tangga,0.000,0.0,1.000,0.0000,Neutral
3,sertu iswanto babinsa kalurahan srihatjo bersa...,0.000,0.0,1.000,0.0000,Neutral
4,kerap termarjinalisasi perempuan perempuan pen...,0.000,0.0,1.000,0.0000,Neutral
...,...,...,...,...,...,...
995,puas deh si istri suami jd tsk anak bgmn agak ...,0.045,0.0,0.955,0.2263,Positive
996,tetap aja kalo anjingan dalam rumah tangga nam...,0.000,0.0,1.000,0.0000,Neutral
997,rizky billar diperiksa sebagai terlapor atas k...,0.000,0.0,1.000,0.0000,Neutral
998,penyidik satreskrim polres metro jakarta selat...,0.000,0.0,1.000,0.0000,Neutral
999,rizky billar ngaku tak menyesal usai ditetapka...,0.000,0.0,1.000,0.0000,Neutral

In [ ]:
print(data["Sentiment"].value_counts())

Neutral     2430
Negative     154
Positive     125
Name: Sentiment, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
import re
import joblib
import pickle
from sklearn import model_selection
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from PIL import Image
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csvdf = pd.read_csv("/content/safitri.csv", sep=";")
df.head()

                                        tweet_cleans  Sentimen
0  kerap termarjinalisasi perempuan perempuan pen...   Neutral
1  tindakan semacam ini dapat dilaporkan kepada p...   Neutral
2         inilah contoh kekerasan dalam rumah tangga   Neutral
3  sertu iswanto babinsa kalurahan srihatjo bersa...   Neutral
4  kerap termarjinalisasi perempuan perempuan pen...   Neutral

In [ ]:
X = df[['tweetns', 'sentimen']]
y = df['sentimen']
print(X.shape)
print(y.shape)

In [ ]:
data.to_csv("new_data.csv")